export enum ErrorCodes {
  UserWithSameEmail = "USER_WITH_SAME_EMAIL",
  UserWithSameDni = "USER_WITH_SAME_DNI",
  UserNotFound = "USER_NOT_FOUND",
  RoleWithSameCode = "ROLE_WITH_SAME_CODE",
  BusinessCategoryWithSameName = "BUSINESS_CATEGORY_WITH_SAME_NAME",
  CityWithSameCode = "CITY_WITH_SAME_CODE",
  BusinessWithSameNit = "BUSINESS_WITH_SAME_NIT",
  SubcategoryWithSameNameAndType = "SUBCATEGORY_WITH_SAME_NAME_AND_TYPE",
  CategoryWithSameNameAndType = "CATEGORY_WITH_SAME_NAME_AND_TYPE",
  ExistingMainHeadquarter = "EXISTING_MAIN_HEADQUARTER",
  ProductCategoryWithSameName = "PRODUCT_CATEGORY_WITH_SAME_NAME",
  InvalidImage = "INVALID_FILE",
  ServiceCategoryWithSameName = "SERVICE_CATEGORY_WITH_SAME_NAME",
  CustomerWithSameEmail = "CUSTOMER_WITH_SAME_EMAIL",
}
